<a href="https://colab.research.google.com/github/MadeehaTassadaq/MadeehaTassadaq/blob/main/date_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [204]:
import pandas as pd
import numpy as np

In [205]:
date=pd.read_csv('orders.csv')

In [206]:
time=pd.read_csv('messages.csv')

In [207]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [208]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [209]:
date['date']=pd.to_datetime(date['date'])

In [210]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [211]:
# extracting year
date['year']=date['date'].dt.year

In [212]:
# extracting month
date['month']=date['date'].dt.month

In [213]:
# extracting month_name
date['month_name']=date['date'].dt.month_name()

In [214]:
# extracting date
date['date_day']=date['date'].dt.day

In [215]:
# EXTRACTING DAY OF WEEK
date['day_of_week']=date['date'].dt.dayofweek

In [216]:
# extracting name of week
date['day_name']=date['date'].dt.day_name()

In [217]:
# is weekend
date['weekend']=np.where(date['day_of_week'].isin([5,6]),1,0)

In [218]:
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,date_day,day_of_week,day_name,weekend
771,2019-06-17,2897,26,1,2019,6,June,17,0,Monday,0
940,2019-03-02,7208,6,1,2019,3,March,2,5,Saturday,1
699,2018-10-06,1160,13,6,2018,10,October,6,5,Saturday,1
440,2018-10-31,4382,23,5,2018,10,October,31,2,Wednesday,0
381,2019-04-12,2837,18,149,2019,4,April,12,4,Friday,0

### Extract week of the year

In [219]:
date['week_of_year']=date['date'].dt.week

AttributeError: 'DatetimeProperties' object has no attribute 'week'

### Extract quarter

In [220]:
date['quarter']=date['date'].dt.quarter

### Extract Semester

In [221]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,date_day,day_of_week,day_name,weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### Extract datetime

In [222]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2024, 8, 8, 16, 27, 16, 922062)

In [223]:
today-date['date']

0     1703 days 16:27:16.922062
1     2185 days 16:27:16.922062
2     2116 days 16:27:16.922062
3     1818 days 16:27:16.922062
4     2041 days 16:27:16.922062
                 ...
995   2131 days 16:27:16.922062
996   2072 days 16:27:16.922062
997   1920 days 16:27:16.922062
998   1985 days 16:27:16.922062
999   1759 days 16:27:16.922062
Name: date, Length: 1000, dtype: timedelta64[ns]

In [224]:
(today-date['date']).dt.days

0      1703
1      2185
2      2116
3      1818
4      2041
       ...
995    2131
996    2072
997    1920
998    1985
999    1759
Name: date, Length: 1000, dtype: int64

In [225]:
today-date['date']/np.timedelta64(1,'M')
today-date['date']/np.timedelta64(1,'Y')

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [226]:
date=pd.DataFrame({
    'date':[21,22,23,34],
    'day_name':['Monday','Tuesday','Wednesday','Thursday'],
    'month':['January','February','March','April'],
    'year':[2021,2022,2023,2024]

                   })

In [227]:
# calculate the time elapsed
date['date']=pd.to_datetime(date['date'])

In [228]:
date

                           date   day_name     month  year
0 1970-01-01 00:00:00.000000021     Monday   January  2021
1 1970-01-01 00:00:00.000000022    Tuesday  February  2022
2 1970-01-01 00:00:00.000000023  Wednesday     March  2023
3 1970-01-01 00:00:00.000000034   Thursday     April  2024